baseURL = 'https://martindbarker.com/'
languageCode = 'en-us'
title = 'Martin D Barker Photography'
theme = 'gallery'

[menu]

[[menu.main]]
  name = "About Me"
  url = "/about"
  weight = 10

[[menu.main]]
  name = "Street"
  url = "/street"
  weight = 11

[[menu.main]]
  name = "Dennistoun"
  url = "/dennistoun"
  weight = 12

[[menu.main]]
  name = "Portraits"
  url = "/Portraits"
  weight = 13

[build]
  timeout = 120

